### PR TITLE
Set upper bounds

### PR DESCRIPTION
**Pull request by jpsamaroo**
I'd like to be able to tag a release of Dagger without having to fix up JuliaDB first, so let's set upper bounds on all deps and upgrade things incrementally.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
CI failures are known, see e.g. #324 

Needs a rebase though.

**Comment by jpsamaroo** [comment]
I believe the CI failures are actually due to a change in a dependency somewhere, which is why previously CI was passing. If I can figure out a valid set of UBs that allow CI to pass, then I'll push them here. Otherwise I can just rebase+merge this and hope that users' code doesn't break...

**Comment by DilumAluthge** [comment]
> If I can figure out a valid set of UBs that allow CI to pass, then I'll push them here.

Look through old Travis CI logs?

**Comment by jpsamaroo** [comment]
If this next CI run passes, then I think we're good to go! Also, since 0.13.0 never got released, we'll stick with that version instead of bumping to 0.13.1.

**Comment by jpsamaroo** [comment]
Closes #324 , #334, #312

**Comment by jpsamaroo** [comment]
1.4 timeout is probably due to some Travis setting somewhere, and I'm not sure which one. I'm going to merge this since it seems otherwise correct.

**Pull request merged**
