### PR TITLE
Update compat and set version to v0.13.2

### PR DESCRIPTION
**Pull request by barche**
This is an attempt to relax some of the compat restrictions, since using JuliaDB with a recent version of Plots is impossible due to the existing restrictions.

### CODE REVIEW

**Comment by barche** [comment]
Despite the green checkmark here, I should mention that locally the tests fail with this change and passed before, so this definitely breaks something.

**Comment by jpsamaroo** [comment]
Green checkmarks are Dagger reverse CI, which don't really make sense to run in a downstream package (@DilumAluthge).

**Comment by barche** [comment]
I think the tests were missing because of the Travis policy changes, I added a simple Github workflow test.

**Comment by barche** [comment]
I have no idea why the tests are failing, so this probably needs attention from a JuliaDB expert.

**Comment by jpsamaroo** [comment]
I'm not sure how the test being pointed to is generating an empty set of `Column`s, but this line needs to handle a `sum` over an empty vector: https://github.com/JuliaData/JuliaDB.jl/blob/53b362b81f247e74e959dd8a0faad5f858423233/src/util.jl#L212

**Comment by quinnj** [comment]
Sorry I didn't see this PR before; I've bumped our dependency compats here: https://github.com/JuliaData/JuliaDB.jl/pull/387. I fixed the `sum(map` case, but there are still a few other failures when running tests locally. I plan to try and look into what's going on as I have a little free time over the next week or so, unless someone beats me to it.

**Pull request closed without merging**
