### PR TITLE
Allowing longer run of tests, updating version of Julia in CI

### PR DESCRIPTION
**Pull request by racinmat**
Now tests run on latest stable Julia instead of 1.4.
Also, I added few prints to tests so they are not killed by 10 minutes of no output. This approach is already used for few other Julia packages.

### CODE REVIEW

**Comment by racinmat** [comment]
Tests don't seem to finish in hour on Julia 1.5.
Given the fact that they finished considerably faster in 1.0 I'm worried what's happening.

**Comment by racinmat** [comment]
Sorry, I didn't read through previous issues closely enough, I'll return the upper bounds.

**Comment by racinmat** [comment]
Ready to merge now. 
image

**Comment by jpsamaroo** [comment]
1.5 is still timing out in Travis. It could be a hang or horrendously slow code path; if you can figure out which it is, that would be super helpful :slightly_smiling_face:

**Comment by racinmat** [comment]
I think it's horrendously slow code path, because on my PC it doesn't get stuck. But tests fail because of something weird between processes. But I have windows, so this might be some windows issue, I want to try this on linux outside of travis.

**Comment by racinmat** [comment]
It's the case of horrendously slow code path, tests finished on my Ubuntu 18.04 in WSL 2, but they took over hour.
Also, could you please add hacktoberfest-accepted label to this PR so it counts to my hacktober participation? Thanks much.

**Comment by jpsamaroo** [comment]
Thanks!

**Comment by racinmat** [comment]
Sorry for bothering, it must be `hacktoberfest-accepted` as label for PR.
The `hacktoberfest` is label for whole repo, allowing any PR to count to hacktoberfest.

**Comment by jpsamaroo** [comment]
Damn Hacktoberfest :smile: Hopefully this does it.

**Comment by racinmat** [comment]
yeah, it does, thanks much

**Pull request merged**
